load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "requests",
    srcs = (["RequestTest.java"]),
    test_class = "sg.edu.ntu.nfs.common.requests.RequestTest",
    deps = [
        "//:common",
        "//:java_test_deps",
    ],
)